# Generated by Django 3.0.3 on 2020-02-16 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0004_auto_20200216_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
    ]
