# Generated by Django 3.0.3 on 2020-02-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200216_2215'),
        ('post', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
    ]
