# Generated by Django 3.0.3 on 2020-02-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200216_2215'),
        ('post', '0003_auto_20200216_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='userprofile.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ManyToManyField(to='userprofile.UserProfile'),
        ),
    ]
