# Generated by Django 3.0.3 on 2020-02-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200216_2215'),
        ('post', '0005_remove_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.UserProfile'),
        ),
    ]
