# Generated by Django 3.0.3 on 2020-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200211_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, to='userprofile.UserProfile'),
        ),
    ]
